### ISSUE TITLE
Can you support the screenshot function? Thank you.

### ISSUE THREAD

**Issue by AtlantisDe** [jfversluis/Plugin.Maui.ScreenRecording#19]
### Can you support the screenshot function? Thank you.
- [ScreenMaster:Screenshot Markup - Apps on Google Play](https://play.google.com/store/apps/details?id=pro.capture.screenshot&hl=en)
- The screenshot function of this APP is very good. You can refer to it.
```#

// For example, the screenshot returns a byte []


```

**Comment by jfversluis** [comment]
Screenshots are supported from .NET MAUI directly. This library focuses on recording the actual screen. Thanks for the suggestion!

**Comment by AtlantisDe** [comment]
### `Screenshot - .NET MAUI` only supports the current APP and does not use MediaProjection
- [Screenshot - .NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/platform-integration/device-media/screenshot?view=net-maui-8.0)

- So I hope your class library directly supports this function
